### ISSUE TITLE
Event join queue and join fight

### ISSUE THREAD

**Issue by damsdev1** [toppev/StrikePracticeAPI#1]
Create an event that detects when a player enters in a queue or joins a fight.
Why these 2 additions?
Concrete example: You create a staff plugin and you want that when a staff in vanish joins the queue or joins a fight, the vanish is deactivated. With this event, it is then possible.

**Comment by toppev** [comment]
I may implement it in the future

As a workaround you could use the _isInQueue_ method https://github.com/toppev/StrikePracticeAPI/blob/77cf84bdee1d842a18623547701cd40da9c997ff/src/main/java/ga/strikepractice/api/StrikePracticeAPI.java#L260 inside an event (e.g PlayerCommandPreprocessEvent)

You can also use the [KitSelectEvent](https://github.com/toppev/StrikePracticeAPI/blob/master/src/main/java/ga/strikepractice/events/KitSelectEvent.java). It's called when a player receives a kit

Sorry for the late response
