### ISSUE TITLE
Problem with Koth Event and Brackets Event

### ISSUE THREAD

**Issue by EduardNLE** [toppev/StrikePracticeAPI#2]
When I create the arenas and configure them they look good and start well

BUT users can break the sand and I don't know why that happens

And with the Sumo and LMS events they can't break that's the weird thing

**Comment by toppev** [comment]
This is for issues with the API. Contact me on spigot or discord for support. You can toggle whether the plugin disables building in the config

> disable-building-without-build-kit: true
