### ISSUE TITLE
I have a problem with maps

### ISSUE THREAD

**Issue by EduardNLE** [toppev/StrikePracticeAPI#4]
When they click on a kit for example (SG, combo etc) it says that there are no arenas available, when in fact they are

You can come to check I'm a server administrator.
The server is OmegaCraft.
The ip of our server is:

Ip: play.OmegaCraft.cl

And the ip of our TeamSpeak3 is:

Ip: ts3.omegacraft.cl

**Comment by toppev** [comment]
Please, I already said it twice. This is not for plugin support, instead contact me on spigot or discord
